export const images = [
    { id: 1, url: "/static/client/1.jpeg", title: "Global Ocean Currents" },
    { id: 2, url: "/static/client/2.jpeg", title: "Cloud Layers Over the Pacific" },
    { id: 3, url: "/static/client/3.jpeg", title: "Oceanic Reflections" },
    { id: 4, url: "/static/client/4.jpeg", title: "Earth's Atmosphere in Motion" },
    { id: 5, url: "/static/client/5.jpeg", title: "Shadows on the Ocean Surface" },
    { id: 6, url: "/static/client/6.jpeg", title: "Expanse of the Blue Planet" },
    { id: 7, url: "/static/client/7.jpeg", title: "Cloud Patterns Above Oceans" },
    { id: 8, url: "/static/client/8.jpeg", title: "Earth's Vast Oceans" },
    { id: 9, url: "/static/client/9.jpeg", title: "Dynamic Weather Systems" },
    { id: 10, url: "/static/client/10.jpeg", title: "Satellite View of the Horizon" },
    { id: 11, url: "/static/client/11.jpeg", title: "Whispers of Wind and Clouds" },
    { id: 12, url: "/static/client/12.jpeg", title: "Ethereal Cloud Formations" },
    { id: 13, url: "/static/client/13.jpeg", title: "Surface Reflections from Space" },
    { id: 14, url: "/static/client/1.jpeg", title: "Atmospheric Layers Seen From Above" },
    { id: 15, url: "/static/client/2.jpeg", title: "Aerial Ocean Serenity" },
    { id: 16, url: "/static/client/3.jpeg", title: "Vast Horizons of Earth" },
    { id: 17, url: "/static/client/4.jpeg", title: "Shimmering Ocean Clouds" },
];
