export const images = [
    { id: 1, url: "/static/client/1.jpeg", title: "" },
    { id: 2, url: "/static/client/2.jpeg", title: "" },
    { id: 3, url: "/static/client/3.jpeg", title: "" },
    { id: 4, url: "/static/client/4.jpeg", title: "" },
    { id: 5, url: "/static/client/5.jpeg", title: "" },
    { id: 6, url: "/static/client/6.jpeg", title: "" },
    { id: 7, url: "/static/client/7.jpeg", title: "" },
    { id: 8, url: "/static/client/8.jpeg", title: "" },
    { id: 9, url: "/static/client/9.jpeg", title: "" },
    { id: 10, url: "/static/client/10.jpeg", title: "" },
    { id: 11, url: "/static/client/11.jpeg", title: "" },
    { id: 12, url: "/static/client/12.jpeg", title: "" },
    { id: 13, url: "/static/client/13.jpeg", title: "" },
    { id: 14, url: "/static/client/1.jpeg", title: "" },
    { id: 15, url: "/static/client/2.jpeg", title: "" },
    { id: 16, url: "/static/client/3.jpeg", title: "" },
    { id: 17, url: "/static/client/4.jpeg", title: "" },
    // { id: 1, url: "/static/client/1.jpg", title: "Galactic Sunrise" },
    // { id: 2, url: "/static/client/1.jpeg", title: "Nebula Dreams" },
    // { id: 3, url: "/static/client/3.jpg", title: "Cosmic Clouds" },
    // { id: 4, url: "/static/client/4.jpg", title: "Celestial Spheres" },
    // { id: 5, url: "/static/client/5.jpeg", title: "Stellar Winds" },
    // { id: 6, url: "/static/client/6.jpeg", title: "Asteroid Fields" },
    // { id: 7, url: "/static/client/7.jpeg", title: "Galactic Core" },
    // { id: 8, url: "/static/client/8.jpeg", title: "Solar Flare" },
    // { id: 9, url: "/static/client/9.jpeg", title: "Lunar Landscape" },
    // { id: 10, url: "/static/client/10.jpeg", title: "Comet Trails" },
    // { id: 11, url: "/static/client/11.jpeg", title: "Supernova Blast" },
    // { id: 12, url: "/static/client/12.jpeg", title: "The Milky Way" },
    // { id: 13, url: "/static/client/13.jpeg", title: "Ringed Planet" },
    // { id: 14, url: "/static/client/14.jpeg", title: "Meteor Shower" },
    // { id: 15, url: "/static/client/15.jpeg", title: "Deep Space" },
    // { id: 16, url: "/static/client/16.jpeg", title: "Interstellar Clouds" },
    // { id: 17, url: "/static/client/17.jpeg", title: "Eclipse View" },
    // { id: 18, url: "/static/client/18.jpeg", title: "Frozen Moon" },
    // { id: 19, url: "/static/client/19.jpeg", title: "Binary Stars" },
    // { id: 20, url: "/static/client/20.jpeg", title: "Galactic Edge" },
    // { id: 21, url: "/static/client/21.jpeg", title: "The Red Planet" },
    // { id: 22, url: "/static/client/22.jpeg", title: "Alien Sunset" },
    // { id: 23, url: "/static/client/23.jpeg", title: "Space Horizon" },
    // { id: 24, url: "/static/client/24.jpeg", title: "Black Hole" },
    // { id: 25, url: "/static/client/25.jpeg", title: "Astral Glow" }
];
