export const images = [
    { id: 1, url: "/static/Images/1.jpg", title: "Galactic Sunrise" },
    { id: 2, url: "/static/Images/2.jpg", title: "Nebula Dreams" },
    { id: 3, url: "/static/Images/3.jpg", title: "Cosmic Clouds" },
    { id: 4, url: "/static/Images/4.jpg", title: "Celestial Spheres" },
    { id: 5, url: "/static/Images/5.jpeg", title: "Stellar Winds" },
    { id: 6, url: "/static/Images/6.jpeg", title: "Asteroid Fields" },
    { id: 7, url: "/static/Images/7.jpeg", title: "Galactic Core" },
    { id: 8, url: "/static/Images/8.jpeg", title: "Solar Flare" },
    { id: 9, url: "/static/Images/9.jpeg", title: "Lunar Landscape" },
    { id: 10, url: "/static/Images/10.jpeg", title: "Comet Trails" },
    { id: 11, url: "/static/Images/11.jpeg", title: "Supernova Blast" },
    { id: 12, url: "/static/Images/12.jpeg", title: "The Milky Way" },
    { id: 13, url: "/static/Images/13.jpeg", title: "Ringed Planet" },
    { id: 14, url: "/static/Images/14.jpeg", title: "Meteor Shower" },
    { id: 15, url: "/static/Images/15.jpeg", title: "Deep Space" },
    { id: 16, url: "/static/Images/16.jpeg", title: "Interstellar Clouds" },
    { id: 17, url: "/static/Images/17.jpeg", title: "Eclipse View" },
    { id: 18, url: "/static/Images/18.jpeg", title: "Frozen Moon" },
    { id: 19, url: "/static/Images/19.jpeg", title: "Binary Stars" },
    { id: 20, url: "/static/Images/20.jpeg", title: "Galactic Edge" },
    { id: 21, url: "/static/Images/21.jpeg", title: "The Red Planet" },
    { id: 22, url: "/static/Images/22.jpeg", title: "Alien Sunset" },
    { id: 23, url: "/static/Images/23.jpeg", title: "Space Horizon" },
    { id: 24, url: "/static/Images/24.jpeg", title: "Black Hole" },
    { id: 25, url: "/static/Images/25.jpeg", title: "Astral Glow" }
];
